title: Recipe Ratings and Cooking Time
description: Final project for DSC 80 at UCSD analyzing Food.com recipes and ratings.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme

show_downloads: false